OpticalNavigation/core/attitude.py, OpticalNavigation/core/const.py, OpticalNavigation/core/find_with_blobs.py, OpticalNavigation/core/find_with_contours.py, OpticalNavigation/core/find_with_kmeans.py, OpticalNavigation/core/opnav.py, OpticalNavigation/core/preprocess.py, OpticalNavigation/core/sense.py, OpticalNavigation/core/ukf.py, OpticalNavigation/simulations/attitudeSim.py, OpticalNavigation/tests/test_attitude.py, OpticalNavigation/tests/test_find.py, OpticalNavigation/tests/test_pipeline.py, OpticalNavigation/tests/test_sixhours.py, main.py, utils/db.py
* updated utils/db.py::OpNavCoordinatesModel
* opnav.py::start() with db entries
* added helpful comments
* moved ukf.py constants to core.const.py
* added alternate detection code (contours, kmeans)
=> Added starting point to OpNav module

communications/command_definitions.py, flight_modes/flight_mode.py, utils/constants.py
This PR implements the CQC CommsProc data generation for verification once on orbit. For more information, see https://cornell.app.box.com/file/766365097328
The algorithm has been verified with the integration teams at NASA.
This PR does not yet give the capability for us to downlink and receive this data yet, though.
=> Random data gen (NASA CQC)

communications/command_definitions.py, drivers/gyro.py, drivers/rtc.py, flight_modes/flight_mode.py, main.py, requirements_pi.txt, utils/constants.py
=> Rtc integration and preliminary RTC driver

flight_modes/flight_mode.py
Judging by the comments in nemo_manager, this is an easy way to pause/resume the nemo thread. 
Matt, I wanted to run this by you to make sure it's the proper way to go about it. 
Signed-off-by: tmf97 <tmf97@cornell.edu>
=> Add nemo pause and resume in PauseBackgroundMode

HITL-tests/hitl_groundstation_tx.py
Makes some small changes to hitl_groundstation_tx to continuously transmit commands and then listen for telemetry.
Signed-off-by: tmf97 <tmf97@cornell.edu>
=> Sequential TX/RX HITL ground station

HITL-tests/sensor_check.py
This PR adds a simple checkout script that can be used to make sure that all the relevant sensors connected to the spacecraft are connected and functional.
This script has been tested on the flight units, and is not used in flight so I feel comfortable merging it.
=> Sensor checkout script

HITL-tests/gom_console.py
Has been tested on flight units. 
Signed-off-by: tmf97 <tmf97@cornell.edu>
=> Make outputs menu clearer

.github/workflows/run-tests.yml, HITL-tests/sensor_check.py, OpticalNavigation/core/attitude.py, OpticalNavigation/core/sense.py, communications/command_definitions.py, communications/satellite_radio.py, drivers/gyro.py, drivers/power/power_controller.py, flight_modes/attitude_adjustment.py, flight_modes/flight_mode.py, flight_modes/opnav_flightmode.py, flight_modes/restart_reboot.py, main.py, pyrightconfig.json, requirements.txt, setup.py, telemetry/sensor.py, telemetry/telemetry.py, utils/db.py
=> Some code cleanups

drivers/power/power_structs.py, flight_modes/attitude_adjustment.py
Fixed the pyright warnings that have been bugging me 🙃 
pyright has no warnings now
Changes might have an affect on ACS flight mode, but should be fine since that will need to be rewritten anyways...
=> Fix pyright warnings

.env.example, communications/command_definitions.py, flight_modes/flight_mode.py, main.py, pyrightconfig.json, utils/constants.py
Adds the Test Flight Mode as an option for the initial flight mode, as specified by a parameter in the .env file
You can run main.py with a .env file with `TEST=1` and see that it works!
=> Add test mode possibility

HITL-tests/gom_console.py, drivers/power/power_controller.py, flight_modes/low_battery.py
Fixes GomOuputs Enum lookup bug
Added type hinting to some gomspace driver functions. Type checker
I'll make some modifications to how the gom drivers work sometime soon as a result of this bug.
=> Gomspace driver Enum fix

HITL-tests/gom_console.py, drivers/power/HITL_testing/HITL_table_test.py, drivers/power/power_controller.py, drivers/power/power_structs.py, flight_modes/low_battery.py, utils/constants.py
Cleaned up the Gom driver, use enums instead of hardcoded values
Type hinting/type checking
=> Type hinting gom driver

.gitignore, communications/README.md, communications/command_definitions.py, communications/commands.py
Updated old command documentation and added docstrings
N/A, just docs
Still need to update box docs
=> Command documentation

main.py
Previous PR made an oopsie. Fixed it. Not sure how it passed CI
flatsat
=> fix logging bug

communications/command_definitions.py
=> electrolysis fix

flight_modes/flight_mode.py
< instead of >
Flatsat
I feel like we have more of these lying around in FSW. Will investigate
=> logic fix for radio

flight_modes/maneuver_flightmode.py, utils/parameters.py
This PR addresses Jira ticket [CISLUNAR-XX](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-XX)     
Changes to maneuver mode
To be flatsat tested
=> Maneuver patch

flight_modes/flight_mode.py, main.py
Fixes bootup rebooting behavior
Flatsat tested during demo
This whole "when do I do a soft reboot" question still needs to be cleanly solved - the current implementation is hacky at best
=> Bootup fix

communications/command_handler.py, communications/commands.py, main.py, tests/command_test.py, tests/gom_config_test.py
Closes #140 
This PR addresses Jira ticket [CISLUNAR-113](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-113)     
Added unit testing,
Still need to update `command_queue_writer.py`
=> Counter fix

communications/ax5043_manager/mock_ax5043_driver.py, communications/ax5043_manager/test_ax5043_driver.py
This PR addresses Jira ticket [CISLUNAR-XX](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-XX)
=> Added TODO comments

communications/downlink.py
Added a todo about bit_inflation
This PR addresses Jira ticket [CISLUNAR-146](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-146)
None
None
None
=> emerald comment task

tests/maneuver_test.py
Added comment suggesting update to documentation of maneuver_test.py.
=> Add comment suggesting update to documentation

HITL-tests/gom_console.py, communications/command_definitions.py, drivers/gom.py, drivers/power/HITL_testing/HITL_table_test.py, drivers/power/HITL_testing/burnwires-test.py, drivers/power/HITL_testing/gom_commands_hitl_test.py, drivers/power/loadswitch.py, drivers/power/power_controller.py, flight_modes/attitude_adjustment.py, flight_modes/flight_mode.py, flight_modes/low_battery.py, flight_modes/maneuver_flightmode.py, flight_modes/restart_reboot.py, pyrightconfig.json, tests/maneuver_test.py
This PR standardizes the gom interface using loadswitch objects. 
Will need to flatsat test this - not sure how good mocking will be.
=> Gom revisit

flight_modes/restart_reboot.py
This PR addresses Jira ticket [CISLUNAR-147](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-147)     
Added a comment in restart_reboot.py indicating that it may be beneficial to indicate the use of the restart FlightMode, similar to how the Low Battery flight mode is documented. 
Reading about the Flight Modes in the documentation was helpful and I noticed only some FlightMode files had comments explaining their use, so adding doc comments to the rest of them may be beneficial
- [x ] Add an x between the brackets if you commented your code well!
=> Added suggestion for documentation comment in restart_reboot.py

.gitignore, OpticalNavigation/tests/test_center_finding.py
This PR addresses Jira ticket [CISLUNAR-XX](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-140)     
- center find feature test now generates a separate directory based on the current unix time
- all results file are placed in this directory
=> Test runs now generate a separate directory

OpticalNavigation/tests/test_reprojections.py, main.py
This PR addresses Jira ticket [CISLUNAR-153](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-153) 
Added in some more areas in main.py to add more documentation for clarity. 
Documentation does not need any testing,  so no tests were implemented and ran.
main.py is mostly documented well; adding some more comments may be helpful for future maintenance.
=> included some TODOs for adding more documentation in main.py

flight_modes/flight_mode.py
This PR addresses Jira ticket [CISLUNAR-155](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-155)     
Added a comment for further documentation on flight_mode.py.
=> add comment for clarification

communications/commands.py, tests/command_test.py, utils/constants.py
This PR adds more in-line documentation to help implement more commands in the future
N/A, just comments
=> Add more comments to help implement commands

OpticalNavigation/simulations/sim/src/opnav_sim.py, pyrightconfig.json, setup.py
This PR addresses Jira ticket [CISLUNAR-178](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-178)
- Ran the sim, was able to properly generate images.
- File paths changed to absolute paths within FSW, based on FLIGHT_SOFTWARE_PATH from utils.constants
=> Opnav sim refactor

OpticalNavigation/core/opnav.py
This PR addresses Jira ticket [CISLUNAR-###](https://jira.cornell.edu/browse/CISLUNAR-###)     
Quick change to make the `calculate_cam_measurements` function public so that other files (and users) can use it, instead of replicating code. How's that for small PRs @tmf97 ?
Not needed, will be merged into other branches and testing will be done there
=> Make calculate_cam_measurements public

flight_modes/flight_mode.py, flight_modes/low_battery.py, main.py, sim/sim_data.py
Sim Out Hardware Calls using a method `step()`, which runs FSW through one-time step. A dictionary is taken in as sensory input, which replaces all sensory hardware calls. A sim_output object is written to, and that replaces any hardware calls for actuation.
TBD. We need to integrate the sim with flight software in order to fully test this.
This pull request sets up the structure for integration from FSW, but in order to test this fully, we need to make some changes on the sim side as well. For now, I leave TODO comments for parts that are not fully defined on the Sim's side yet.
=> Draft Sim Implementation/Refactor

.pre-commit-config.yaml
Changed version of black to 22.3.0
=> changed pre commit dependency
